---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-db
  labels:
    app: aqua-db
spec:
  template:
    metadata:
      labels:
        app: aqua-db
      name: aqua-db
      namespace: aqua
    spec:
      serviceAccount: aqua-sa
      containers:
      - name: aqua-db
        image: registry.aquasec.com/database:4.2
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aqua-db
                key: password
        ports:
        - containerPort: 5432
          protocol: TCP