apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: aqua-windows-agent
    aqua.component: enforcer
  name: aqua-windows-agent
  namespace: aqua
spec:
  selector:
    matchLabels:
      app: aqua-windows-agent
  template:
    metadata:
      labels:
        app: aqua-windows-agent
        aqua.component: windows-enforcer
      name: aqua-windows-agent
      namespace: aqua
      annotations:
        container.apparmor.security.beta.kubernetes.io/aqua-windows-agent: unconfined
    spec:
      containers:
      - env:
        - name: AQUA_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AQUA_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: windows-enforcer-token
              optional: true
        envFrom:
        - configMapRef:
            name: aqua-csp-windows-enforcer
        image: 934027998561.dkr.ecr.us-west-2.amazonaws.com/aquaagentwindowsinstaller:2022.4.196 # mcr.microsoft.com/windows/servercore:ltsc2022
        command:
        - powershell.exe
        - -command
        - $argList=@("/I","AquaAgentWindowsInstaller.msi","AQUA_TOKEN=$Env:AQUA_TOKEN","AQUA_SERVER=$Env:AQUA_SERVER","AQUA_ENFORCER_TYPE=$Env:AQUA_ENFORCER_TYPE","/qn","/lv AquaAgentWindowsInstaller.install.log");
        - $result=Start-Process -FilePath msiexec.exe -ArgumentList $argList -Wait;
        - Get-Content AquaAgentWindowsInstaller.install.log;
        - While (Get-Service slkd){ Start-Sleep -s 30 } 
        imagePullPolicy: Always
#        resources:
#          limits:
#            cpu: 1000m
#            memory: 1.5Gi
#          requests:
#            cpu: 350m
#            memory: 512Mi
        startupProbe:
          exec:
            command: 
            - powershell.exe
            - -c
            - Get-Service -Name slkd
          initialDelaySeconds: 60
          periodSeconds: 30
        livenessProbe:
          exec:
            command: 
            - powershell.exe
            - -c
            - Get-Service -Name slkd
          initialDelaySeconds: 60
          periodSeconds: 180
        readinessProbe:
          exec:
            command: 
            - powershell.exe
            - -c
            - Get-Service -Name slkd # | Where-Object {$_.Status -eq "Running"}
          initialDelaySeconds: 60
          periodSeconds: 180
        lifecycle:
          preStop:
            exec:
              command:
              - powershell.exe
              - -command
              - $argList=@("/X","AquaAgentWindowsInstaller.msi","/qn","/L*vx c:\AquaAgentWindowsInstaller.remove.log","/norestart");
              - $result=Start-Process -FilePath msiexec.exe -ArgumentList $argList -Wait 
        name: aqua-windows-agent
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\SYSTEM"
      nodeSelector:
        kubernetes.io/os: windows
      hostNetwork: true
      dnsPolicy: ClusterFirst
      hostPID: true
      imagePullSecrets:
       - name: ecr-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: aqua-sa
      serviceAccountName: aqua-sa
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
