apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Aqua Scanner username and password
  labels:
    deployedby: aqua-yaml
  name: aqua-scanner
  namespace: aqua
type: Opaque
data:
  # Aqua Scanner Username - Base64 Encoded
  AQUA_SCANNER_USERNAME: ""
  # Aqua Scanner Password - Base64 Encoded
  AQUA_SCANNER_PASSWORD: ""
  # Aqua Server IP/Domain followed by HTTPS port - Defaults to aqua-web if the scanner is being deployed to the same cluster.
  AQUA_SERVER: "aqua-web:443"
---
apiVersion: v1
data:
 # Please follow instruction in document to generate new SSL certs
 server.key: 
 server.crt: 
kind: Secret
metadata:
  annotations:
    description: Kube Enforcer SSL certificates to communicate with Kube API server
  labels:
    deployedby: aqua-yaml
  name: kube-enforcer-ssl
  namespace: aqua
type: Opaque