#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: aqua-scanner-pvc
#  namespace: aqua
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-scanner
  namespace: aqua
  labels:
    app: aqua-scanner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aqua-scanner
    spec:
      serviceAccountName: aqua-sa
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      containers:
        - name: kube-scanner
          image: registry.aquasec.com/scanner:6.2
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "/opt/aquasec/scannercli daemon --host https://${AQUA_SERVER} --user ${AQUA_SCANNER_USERNAME} --password ${AQUA_SCANNER_PASSWORD} --no-verify"]
          env:
            - name: AQUA_SCANNER_LOGICAL_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            #   #Optional environment variable, to set the max amount of consecutive attempts before back off. There will be a random interval between connection attempts.
            #   #(This and AQUA_CONNECTIVITY_BACKOFF_DURATION should both be set to trigger the backoff mechanism)
            # - name: AQUA_MAX_CONSECUTIVE_CONNECTION_ATTEMPTS
            #   value: "5"
            #   #Optional environment variable, to set the amount of time (in seconds) in which there is no attempt to connect.
            #   #Once this duration passes, the reconnect mechanisim will be triggered again till max attempts.
            # - name: AQUA_CONNECTIVITY_BACKOFF_DURATION
            #   value: "120"
            #   # Scanner's private key for HTTPS and Mutual Auth with offline CyberCenter
            # - name: AQUA_PRIVATE_KEY
            #   value: "/opt/aquasec/ssl/key.pem"
            #   # Scanner's public key for HTTPS and Mutual Auth with offline CyberCenter
            # - name: AQUA_PUBLIC_KEY
            #   value: "/opt/aquasec/ssl/cert.pem"
            #   # Scanner's root CA cert for HTTPS and Mutual Auth. The root CA certificate file should be mutual for both CyberCenter and Scanner certificates
            # - name: AQUA_ROOT_CA
            #   value: "/opt/aquasec/ssl/ca.pem"
            # - name: OFFLINE_CC_MTLS_ENABLE # Set this to 1 to establish mTLS connection with CyberCenter
            #   value: "1"
          envFrom:
          - secretRef:
              name: aqua-scanner
          volumeMounts:
            #- name: "docker-socket-mount"
            #  mountPath: "/var/run/docker.sock"
            - name: "ssl-certs"
              mountPath: "/etc/ssl/certs"
              readOnly: true
#            - mountPath: /opt/aquascans
#              name: aquascans
      volumes:
        #- name: "docker-socket-mount"
        #  hostPath:
        #    path: "/var/run/docker.sock"
        - name: "ssl-certs"
          secret:
            secretName: "aqua-scanner"
            items:
            - key: aqua-web-root-cert
              path: aqua-ssl.crt
#        - name: aquascans
#          persistentVolumeClaim:
#            claimName: aqua-scanner-pvc
      imagePullSecrets:
        - name: aqua-registry
  selector:
    matchLabels:
      app: aqua-scanner