---
# Replace {AQUA_SCANNER_USERNAME}, & {AQUA_SCANNER_PASSWORD} \
#    with the credentials of an Aqua user with the Scanner role.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aqua-scanner
  name: aqua-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-scanner
  template:
    metadata:
      labels:
        app: aqua-scanner
      name: aqua-scanner
    spec:
      # To run Aqua components as a non-privileged account
      # uncomment spec.template.spec.securityConext field:
      #securityContext:
      #  runAsUser: 11431
      #  runAsGroup: 11433
      #  fsGroup: 11433
      serviceAccount: aqua-sa
      restartPolicy: Always
      containers:
      - name: aqua-scanner
        image: registry.aquasec.com/scanner:5.3
        imagePullPolicy: Always
        args:
        - daemon
        - --direct-cc
        - --user
        - '{AQUA_SCANNER_USERNAME}'
        - --password
        - '{AQUA_SCANNER_PASSWORD}'
        - --host
        - http://aqua-web:8080
        env:
        - name: AQUA_SCANNER_LOGICAL_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        # - name: AQUA_PRIVATE_KEY # Scanner's private key for HTTPS and Mutual Auth with offline CyberCenter
        #   value: "/opt/aquasec/ssl/key.pem"
        # - name: AQUA_PUBLIC_KEY # Scanner's root CA cert for HTTPS and Mutual Auth. The root CA certificate file should be mutual for both CyberCenter and Scanner certificates
        #   value: "/opt/aquasec/ssl/ca.pem"
        # - name: OFFLINE_CC_MTLS_ENABLE # Set this to 1 to establish mTLS connection with CyberCenter
        #   value: "1"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
