---
apiVersion: v1
kind: Service
metadata:
  name: aqua-gateway
  namespace: aqua
  labels:
    app: aqua-gateway
spec:
  type: ClusterIP
  ports:
    - port: 3622
    - port: 8443
  selector:
    app: aqua-gateway
