---

apiVersion: v1
kind: Service
metadata:
  name: aqua-lb
  labels:
    app: envoy
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: healthserver
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: envoy