---
USERNAME: ""
PASSWORD: ""
ENFORCER_VERSION: ""
TOKEN: ""
GATEWAY_ENDPOINT: ""
INSTALL_PATH: "/opt"
ENFORCER_RUNC_DIRECTORY: "{{ INSTALL_PATH }}/aqua-runc"
ENFORCER_RUNC_FS_DIRECTORY: "{{ ENFORCER_RUNC_DIRECTORY }}/aqua-enforcer"
SYSTEMD_FOLDER: "/etc/systemd/system"
ENFORCER_SERVICE_FILE_NAME: "aqua-enforcer.service"
ENFORCER_SERVICE_TEMPLATE_FILE_NAME: "aqua-enforcer.template.service"
ENFORCER_SERVICE_TEMPLATE_FILE_NAME_OLD: "aqua-enforcer.template.old.service"
RUN_SCRIPT_FILE_NAME: "run.sh"
RUN_SCRIPT_TEMPLATE_FILE_NAME: "run.template.sh"
ENFORCER_SERVICE_SYSTEMD_FILE_PATH: "{{ SYSTEMD_FOLDER }}/{{ ENFORCER_SERVICE_FILE_NAME }}"
ENFORCER_RUNC_CONFIG_FILE_NAME: "config.json"
ENFORCER_RUNC_TAR_FILE_NAME: "aqua-host-enforcer.{{ ENFORCER_VERSION }}.tar"
ENFORCER_SELINUX_POLICY_FILE_NAME: "aquavme"
ENFORCER_DOWNLOAD_BASEURL: "https://download.aquasec.com/internal/host-enforcer"
