apiVersion: v1
kind: Secret
metadata:
  name: aqua-server-credentials
  namespace: aqua
type: Opaque
data:
  username: <aqua_server_useranme_in_base64_encoded>
  password: <aqua_server_password_in_base64_encoded>