# Create a PVC for the Aqua Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aqua-db-pvc
  namespace: aqua
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi